- Develope:
    - IT Tools:
        - abbr: IT
          href: https://tools.moerman.online
          icon: mdi-tools.png
          description: Handy IT Tools for developers
    - Github:
        - abbr: GH
          description: My GitHub Repository
          icon: github.png
          href: https://github.com/
    - Microsft Azure:
        - abbr: AZ
          description: Microsoft Azure Portal
          icon: azure.png
          href: https://portal.azure.com/
    - Microsft 365:
        - abbr: M3
          description: Microsoft 365 Admin Portal
          icon: office.png
          href: https://admin.microsoft.com/
- Network:
    - UDM Pro:
        - abbr: UD
          icon: unifi.png
          description: Unifi UDM Pro firewall
          href: https://shelob.moerman.online
    - Homeserver iPMI:
        - abbr: IP
          icon: supermicro.png
          description: Homeserver iPMI OOB Access
          href: https://remote.moerman.online
    - CloudFlare:
        - abbr: CF
          description: Cloudflare public domain configurations
          icon: cloudflare.png
          href: https://dash.cloudflare.com/
- Home:
    - iCloud:
        - abbr: IC
          href: https://icloud.com
          icon: icloud.png
          description: iCloud web portal
    - Paperless AI:
        - abbr: PA
          description: Paperless AI scanner
          icon: paperless.png
          href: https://paper-ai.moerman.online
    - Boekhouding:
        - abbr: JR
          description: Jortt boekhoudprogramma
          icon: books.png
          href: https://jortt.nl
