- My Home:
    - Mealie:
        href: https://mealie.moerman.online
        icon: mealie.png
        description: Mealie recepten
        siteMonitor: https://mealie.moerman.online
        showStats: true
        statusStyle: 'dot'
        widget:
            type: mealie
            url: https://mealie.moerman.online
            key: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb25nX3Rva2VuIjp0cnVlLCJpZCI6ImE3NDVhMDBkLWZkZTYtNDE2MS05MGMwLTMzYjgxZGUxZDk4MSIsIm5hbWUiOiJIb21lcGFnZSIsImludGVncmF0aW9uX2lkIjoiZ2VuZXJpYyIsImV4cCI6MTg5ODc1NTc2Mn0.BQkSXg8Vk85WkdlFSodVmtTCXo4yCspvidLF1z7o49A
            version: 2
    # - IT Tools:
    #     href: https://tools.moerman.online
    #     icon: mdi-tools.png
    #     description: Handy IT Tools for developers
    #     siteMonitor: https://tools.moerman.online
    #     showStats: true
    #     statusStyle: 'dot'
    - Paperless:
        href: https://paper.moerman.online
        icon: paperless.png
        description: Paperless document archief
        siteMonitor: https://paper.moerman.online
        showStats: true
        statusStyle: 'dot'
        widget:
          type: paperlessngx
          url: https://paper.moerman.online
          key: 4ec4a746e9d6c197294dc9d7b7297b5d0e03cf78
    - Home Assistant:
        href: https://ha.moerman.online/
        icon: home-assistant.png
        description: Home Assistant home automation
        siteMonitor: https://ha.moerman.online/
        showStats: true
        statusStyle: 'dot'
    - Jellyfin:
        icon: jellyfin.png
        description: Kijk Films & Series
        href: https://media.moerman.online
        showStats: true
        statusStyle: 'dot'
        siteMonitor: https://media.moerman.online
    - VSCode Server:
        href: https://code.moerman.online/
        description: Visual Studio Code Server
        icon: vscode.png
        siteMonitor: https://code.moerman.online/
        showStats: true
        statusStyle: 'dot'
    - Authentik:
        href: https://auth.moerman.online
        icon: authentik.png
        description: Authentik authentication system
        siteMonitor: https://auth.moerman.online
        showStats: true
        statusStyle: 'dot'
        widget:
            type: authentik
            url: https://auth.moerman.online
            key: dqumCnc2c1lDnZVnH8J48mNC8ZN2ddqSl1zrDqIGix09cwDZcCVO3y3gdhFj
- Media Collectors:
    - Film Collector:
        href: https://media.moerman.online/movies
        description: Verzamel en download Films
        icon: radarr.png
        siteMonitor: https://media.moerman.online/movies
        showStats: true
        statusStyle: 'dot'
        widget:
          type: radarr
          url: http://10.0.0.3:7878
          key: "def66c0449264a8d8e3722c34ff1f6f0"
    - TV Series Collector:
        icon: sonarr.png
        description: Verzamel en download Series
        href: https://media.moerman.online/tvshows
        siteMonitor: https://media.moerman.online/tvshows
        showStats: true
        statusStyle: 'dot'
        widget:
          type: sonarr
          url: http://10.0.0.3:8989
          key: "965f0c834f3a4eaf8ab9f74fa8927b52"
    - Book Collector:
        icon: readarr.png
        description: Verzamel en download e-books
        href: https://media.moerman.online/books
        showStats: true
        statusStyle: 'dot'
        siteMonitor: https://media.moerman.online/books
        widget:
          type: readarr
          url: http://10.0.0.3:8787/books
          key: "109dce73b64644ae937178c23ad6fd58"
    - Music Collector:
        icon: lidarr.png
        description: Verzamel en download music
        href: https://media.moerman.online/music
        showStats: true
        statusStyle: 'dot'
        siteMonitor: https://media.moerman.online/music
        widget:
          type: lidarr
          url: http://10.0.0.3:8686
          key: "37e447cc538d4bb9a31587b61018dcfd"
    - Ondertiteling Collector:
        icon: bazarr.png
        description: Zoek en download ondertiteling
        href: https://media.moerman.online/subs
        siteMonitor: https://media.moerman.online/subs
        showStats: true
        statusStyle: 'dot'
        widget:
          type: bazarr
          url: http://10.0.0.3:6767/subs
          key: "1e1e6d8d7802211946a19b0106a73c3a"
- Media Downloaders:
    - Media Aanvrager:
        description: Zoek en vraag Films & Series
        href: https://requests.moerman.online
        icon: jellyseerr.png
        siteMonitor: https://requests.moerman.online
        showStats: true
        statusStyle: 'dot'
        widget:
            type: jellyseerr
            url: http://10.0.0.3:5055
            key: "MTczOTUyMzUxMjIzMjk3ODc0OTdhLWQ3NDktNGVmOC04NGY1LTVlOGYxZjA0ZThjOQ=="
    - Usenet Downloader:
        description: Download Usenet files
        icon: sabnzbd.png
        href: https://media.moerman.online/nzb
        siteMonitor: https://media.moerman.online/nzb
        showStats: true
        statusStyle: 'dot'
        widget:
          type: sabnzbd
          url: http://10.0.0.3:8008
          key: "c6375492f12f421a887cf43d1ae6e318"
    - Torrents Downloader:
        description: Download Torrent files
        icon: qbittorrent.png
        href: https://torrent.moerman.online
        siteMonitor: https://torrent.moerman.online
        showStats: true
        statusStyle: 'dot'
        widget:
          type: qbittorrent
          url: http://qbittorrent:8080
          username: "admin"
          password: "678ZT4fds"
    - Index Collector:
        icon: prowlarr.png
        description: Usenet en Torrentsite Indexer
        href: https://media.moerman.online/index
        siteMonitor: https://media.moerman.online/index
        showStats: true
        statusStyle: 'dot'
        widget:
          type: prowlarr
          url: http://10.0.0.3:9696
          key: "ec43e00d634a4fe18706badd3506b0c7"
- My Cluster:
    - Komodo:
        href: https://komodo.moerman.online/
        description: Komodo Docker management portal
        icon: portainer.png
        siteMonitor: https://komodo.moerman.online/
        showStats: true
        statusStyle: 'dot'
    - Grafana:
        href: https://grafana.moerman.online/
        description: Grafana dashboards
        icon: grafana.png
        siteMonitor: https://grafana.moerman.online/
        showStats: true
        statusStyle: 'dot'
    - TrueNAS:
        href: https://truecommand.moerman.online/
        description: TrueNAS TrueCommand
        icon: https://www.svgrepo.com/show/331613/truenas.svg
        siteMonitor: https://truecommand.moerman.online/
        showStats: true
        statusStyle: 'dot'
        widget:
            type: truenas
            url: http://10.0.0.10
            key: 1-NZFwZtLsNT5CKJSNxCNQ3HZD60bNcs5Rwzudcw0IDYojBWcP9cncsHvxHtC4qu0L
            enablePools: true # optional, defaults to false
            nasType: scale # defaults to scale, must be set to 'core' if using enablePools with TrueNAS Core
    - Backup:
        href: https://backup.moerman.online
        description: Kopia backup service
        icon: kopia.png
        siteMonitor: https://backup.moerman.online
        showStats: true
        statusStyle: 'dot'
    - Scheduler:
        href: https://n8n.moerman.online
        description: n8n Workflow automation
        icon: n8n.png
        siteMonitor: https://n8n.moerman.online
        showStats: true
        statusStyle: 'dot'
    - Repository:
        href: https://registry.moerman.online
        description: Git and Container repositories
        icon: gitea.png
        siteMonitor: https://registry.moerman.online
        showStats: true
        statusStyle: 'dot'
        widget:
            type: gitea
            url: https://registry.moerman.online
            key: d2a3cf0c20e1a5b8e2bc1d5886b998c0c507bf7a
    - Traefik:
        icon: traefik.png
        description: Traefik Dashboard
        href: https://traefik.moerman.online
        siteMonitor: https://traefik.moerman.online/
        showStats: true
        statusStyle: 'dot'
        widget:
            type: traefik
            url: http://10.0.0.3:8080
            # username: username # optional
            # password: password # optional
    # - Uptime Kuma:
    #     icon: uptime.png
    #     description: Uptime Kuma Dashboard
    #     href: https://uptime.moerman.online
    #     siteMonitor: https://uptime.moerman.online/