- resources:
    label: System
    expanded: true
    units: metric
    refresh: 3000
    uptime: true
    cpu: true
    cputemp: true
    tempmin: 0
    tempmax: 90
    memory: true
- resources:
    label: Network
    network: true
    expanded: true
- resources:
    label: Storage
    expanded: true
    disk:
        - /mnt/data
        - /
- unifi_console:
    url: https://10.0.0.1
    username: homepage
    password: B9VA9oYUmg0T1MZ
- datetime:
    text_size: l
    format:
      dateStyle: short
      timeStyle: short
      hourCycle: h23